importing the dependencies


In [1]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

data collection and data preprocessing

In [25]:
movies_data = pd.read_csv('/content/movies.csv', engine='python', on_bad_lines='skip')

In [3]:
movies_data.head()

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
0,0,237000000,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
1,1,300000000,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,285,ocean drug abuse exotic island east india trad...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
2,2,245000000,Action Adventure Crime,http://www.sonypictures.com/movies/spectre/,206647,spy based on novel secret agent sequel mi6,en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
3,3,250000000,Action Crime Drama Thriller,http://www.thedarkknightrises.com/,49026,dc comics crime fighter terrorist secret ident...,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,Christian Bale Michael Caine Gary Oldman Anne ...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Christopher Nolan
4,4,260000000,Action Adventure Science Fiction,http://movies.disney.com/john-carter,49529,based on novel mars medallion space travel pri...,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,Taylor Kitsch Lynn Collins Samantha Morton Wil...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton


In [4]:
movies_data.shape

(403, 24)

In [5]:
selected_features = ['genres','keywords','tagline','cast','director']
print(selected_features)

['genres', 'keywords', 'tagline', 'cast', 'director']


In [6]:
for feature in selected_features:
  movies_data[feature]=movies_data[feature].fillna('')

In [7]:
combined_features = movies_data['genres']+' '+movies_data['keywords']+' '+movies_data['tagline']+' '+movies_data['cast']+' '+movies_data['director']

In [8]:
print(combined_features)

0      Action Adventure Fantasy Science Fiction cultu...
1      Adventure Fantasy Action ocean drug abuse exot...
2      Action Adventure Crime spy based on novel secr...
3      Action Crime Drama Thriller dc comics crime fi...
4      Action Adventure Science Fiction based on nove...
                             ...                        
398    Crime Thriller casino thief revenge heist las ...
399    Adventure Animation Family hunter mountains ga...
400    Adventure Action Science Fiction based on nove...
401    War winter sniper world war ii stalingrad Some...
402    Adventure Action Comedy Thriller hunter bounty...
Length: 403, dtype: object


In [9]:
vectorizer = TfidfVectorizer()

In [10]:
feature_vectors = vectorizer.fit_transform(combined_features)

In [11]:
print(feature_vectors)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 11269 stored elements and shape (403, 3532)>
  Coords	Values
  (0, 22)	0.059206982280134074
  (0, 34)	0.058398521334607274
  (0, 1068)	0.08732372269015282
  (0, 2758)	0.08598791925625976
  (0, 1101)	0.08598791925625976
  (0, 741)	0.24224048558379088
  (0, 602)	0.22667043222098426
  (0, 1203)	0.15786601479685244
  (0, 2921)	0.3003203289357843
  (0, 3362)	0.13699092260524895
  (0, 633)	0.22667043222098426
  (0, 2898)	0.20005325019032166
  (0, 1004)	0.24224048558379088
  (0, 3104)	0.07232426640108679
  (0, 3473)	0.12442579089197897
  (0, 2269)	0.10739546741780417
  (0, 2341)	0.22667043222098426
  (0, 2712)	0.15194655523590037
  (0, 3477)	0.20705448485072694
  (0, 3525)	0.20705448485072694
  (0, 2706)	0.20705448485072694
  (0, 2856)	0.24224048558379088
  (0, 3392)	0.24224048558379088
  (0, 2969)	0.20005325019032166
  (0, 1787)	0.24224048558379088
  :	:
  (402, 34)	0.0547156874418112
  (402, 3104)	0.06776322181491694
  (402, 3127

cosine_similarity

In [12]:
similarity = cosine_similarity(feature_vectors)

In [13]:
print(similarity)

[[1.         0.06388365 0.0323865  ... 0.05649536 0.0518049  0.01138064]
 [0.06388365 1.         0.02658978 ... 0.00828191 0.0133871  0.02157182]
 [0.0323865  0.02658978 1.         ... 0.0456662  0.03768043 0.00699433]
 ...
 [0.05649536 0.00828191 0.0456662  ... 1.         0.         0.00587289]
 [0.0518049  0.0133871  0.03768043 ... 0.         1.         0.01340687]
 [0.01138064 0.02157182 0.00699433 ... 0.00587289 0.01340687 1.        ]]


In [14]:
print(similarity.shape)

(403, 403)


Getting the movie name from the user


In [33]:
movie_name = input('Enter your favourite movie name : ')

Enter your favourite movie name : iron man


In [16]:
list_of_all_titles = movies_data['title'].tolist()
print(list_of_all_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [34]:
find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)
print(find_close_match)

['Iron Man', 'Iron Man 3', 'Iron Man 2']


In [35]:
if find_close_match:
    close_match = find_close_match[0]
    print(close_match)
else:
    print("No close match found for the entered movie name. Please ensure you typed a movie name and try again.")
    close_match = None # Set to None to avoid further errors if no match is found

Iron Man


In [36]:
if close_match is not None:
    index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]
    print(index_of_the_movie)
else:
    print("Cannot find the index of the movie as no close match was found.")
    index_of_the_movie = None # Set to None to prevent further errors

68


In [44]:
similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, np.float64(0.02106203660363296)), (1, np.float64(0.04568276579494181)), (2, np.float64(0.007244407623924561)), (3, np.float64(0.0037982528892014492)), (4, np.float64(0.019935993123830063)), (5, np.float64(0.006879086703404288)), (6, np.float64(0.09549921526784798)), (7, np.float64(0.1992637854182463)), (8, np.float64(0.0036606723893154243)), (9, np.float64(0.050816614717395986)), (10, np.float64(0.05282813207762105)), (11, np.float64(0.005785838042058177)), (12, np.float64(0.00733360663588103)), (13, np.float64(0.006210889681648828)), (14, np.float64(0.06452882805211607)), (15, np.float64(0.0032825871829785134)), (16, np.float64(0.1922585657400827)), (17, np.float64(0.006533998747341847)), (18, np.float64(0.03956322450457696)), (19, np.float64(0.0719121410895815)), (20, np.float64(0.04622664918769002)), (21, np.float64(0.0057647057993156225)), (22, np.float64(0.0031919438883477903)), (23, np.float64(0.0029401984818578928)), (24, np.float64(0.005571421895736485)), (25, np.float64(0

In [38]:
len(similarity_score)

403

In [39]:
sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)
print(sorted_similar_movies)

[(68, np.float64(1.0000000000000002)), (79, np.float64(0.3581680172138881)), (31, np.float64(0.2740617591835329)), (7, np.float64(0.1992637854182463)), (16, np.float64(0.1922585657400827)), (26, np.float64(0.17040161458564787)), (85, np.float64(0.15298364729267888)), (182, np.float64(0.1323848511212133)), (353, np.float64(0.12463704938367978)), (131, np.float64(0.11518473718707917)), (138, np.float64(0.10605898907635587)), (46, np.float64(0.1038395166811214)), (64, np.float64(0.09899376632420001)), (203, np.float64(0.09847013632930052)), (6, np.float64(0.09549921526784798)), (307, np.float64(0.09433148333177982)), (174, np.float64(0.09194597472786938)), (169, np.float64(0.09107569978536333)), (101, np.float64(0.09070253067064286)), (126, np.float64(0.08990406243300263)), (94, np.float64(0.08965577242248854)), (396, np.float64(0.08825855314238445)), (198, np.float64(0.0879186760459539)), (205, np.float64(0.08783838717507818)), (318, np.float64(0.0873490002560239)), (356, np.float64(0.08

In [40]:
print('Movies suggested for you: \n')

i=1
for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  if(i<30):
    print(i,'.',title_from_index)
    i+=1

Movies suggested for you: 

1 . Iron Man
2 . Iron Man 2
3 . Iron Man 3
4 . Avengers: Age of Ultron
5 . The Avengers
6 . Captain America: Civil War
7 . Captain America: The Winter Soldier
8 . Ant-Man
9 . Tropic Thunder
10 . G-Force
11 . The Last Airbender
12 . X-Men: Days of Future Past
13 . X-Men: Apocalypse
14 . X2
15 . Tangled
16 . The Expendables 3
17 . The Incredible Hulk
18 . Captain America: The First Avenger
19 . X-Men: First Class
20 . Thor: The Dark World
21 . Guardians of the Galaxy
22 . Enemy of the State
23 . R.I.P.D.
24 . Sherlock Holmes: A Game of Shadows
25 . Surf's Up
26 . Sherlock Holmes
27 . X-Men: The Last Stand
28 . TRON: Legacy
29 . The Jungle Book


Movie Recommendation System

In [45]:
movie_name = input('Enter your favourite movie name : ')
list_of_all_titles = movies_data['title'].tolist()
find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)
close_match = find_close_match[0]
index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]
similarity_score = list(enumerate(similarity[index_of_the_movie]))
sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)
print('Movies suggested for you: \n')

i=1
for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  if(i<30):
    print(i,'.',title_from_index)
    i+=1

Enter your favourite movie name : avatar
Movies suggested for you: 

1 . Avatar
2 . Guardians of the Galaxy
3 . Star Trek Beyond
4 . Star Trek Into Darkness
5 . Gravity
6 . Clash of the Titans
7 . Terminator Salvation
8 . Star Trek
9 . Furious 7
10 . Terminator Genisys
11 . Planet of the Apes
12 . Allegiant
13 . Oz: The Great and Powerful
14 . Men in Black
15 . Treasure Planet
16 . Men in Black II
17 . The Fifth Element
18 . The Last Samurai
19 . X-Men: Days of Future Past
20 . The Fast and the Furious
21 . John Carter
22 . The Chronicles of Riddick
23 . Spider-Man 2
24 . Contact
25 . Superman Returns
26 . Home
27 . Jupiter Ascending
28 . Wrath of the Titans
29 . The Wolverine
